version: '3.9'
services:
  friends:
    build:
      context: friends
      target: builder
    container_name: friends
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    restart: "on-failure"
 
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    secrets:
      - db-pass
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-pass
      POSTGRES_USER: user
      POSTGRES_DB: chat

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80

secrets:
  db-pass:
    file: db/pass.txt