apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend
  name: authorization
  labels:
    app: authorization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization
  template:
    metadata:
      labels:
        app: authorization
  spec:
    containers:
      - name: authorization
        image: sonicsmall/authorization:latest
        ports:
          - containerPort:  8000