apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  spec:
    containers:
      - name: authorization
        image: sonicsmall/authorization:latest
        ports:
          - containerPort:  8000
        labels:
          app: app
